# Generated by Django 5.0.7 on 2024-07-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=24, verbose_name='pièce')),
                ('issue', models.TextField(verbose_name="Type d'incident")),
                ('details', models.TextField(verbose_name='Informations complémentaires')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.apartment')),
            ],
        ),
    ]
