# Generated by Django 5.0.7 on 2024-07-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.AlterModelOptions(
            name='typeissue',
            options={'verbose_name': "Type d'incident", 'verbose_name_plural': "Types d'incidents"},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='room',
        ),
    ]
