# Generated by Django 5.0.7 on 2024-07-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_options_alter_typeissue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Incident', 'verbose_name_plural': 'Incident'},
        ),
        migrations.AddField(
            model_name='issue',
            name='room',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
