# Generated by Django 5.0.7 on 2024-07-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_remove_issue_room_issue_room'),
        ('main', '0021_alter_room_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='main.apartment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='room',
            field=models.ManyToManyField(related_name='issues', to='main.room'),
        ),
    ]
