# Generated by Django 5.0.7 on 2024-07-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issue_apartment_alter_issue_room'),
        ('project', '0021_alter_room_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='project.apartment'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='room',
        ),
        migrations.AddField(
            model_name='issue',
            name='room',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='project.room'),
            preserve_default=False,
        ),
    ]
