# Generated by Django 5.0.7 on 2024-07-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_remove_issue_room_issue_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeIssue',
            new_name='IssueType',
        ),
    ]
