# Generated by Django 5.0.7 on 2024-08-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_rename_typeissue_issuetype'),
        ('project', '0029_rename_number_of_bathrooms_apartment_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='room',
        ),
        migrations.AddField(
            model_name='issue',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.room'),
            preserve_default=False,
        ),
    ]
