# Generated by Django 5.0.7 on 2024-07-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apartment_laundry_room_alter_apartment_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('BE', 'Chambre'), ('BA', 'Salle de bain'), ('KI', 'Cuisine'), ('LI', 'Salon'), ('LA', 'Buanderie'), ('EN', 'Entrée')], default='', max_length=24),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='bedroom',
        ),
        migrations.AddField(
            model_name='apartment',
            name='bathroom',
            field=models.ManyToManyField(related_name='bathroom', to='main.room', verbose_name='Salle de bain'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedroom',
            field=models.ManyToManyField(to='main.room', verbose_name='Chambre'),
        ),
    ]
