# Generated by Django 5.0.7 on 2024-07-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_apartment_bathroom_remove_apartment_bedroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='laundry_room',
        ),
    ]
