# Generated by Django 5.0.7 on 2024-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_apartment_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='rooms',
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='main.room'),
        ),
    ]
