# Generated by Django 5.0.7 on 2024-07-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0028_remove_apartment_kitchen_room_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Nom')),
                ('room', models.CharField(choices=[('KITCHEN', 'Cuisine'), ('BEDROOMS', 'Chambres'), ('BATHROOM', 'Salle de bain'), ('COMMON', 'Espaces communs')], default='KITCHEN', max_length=24, verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_HANDLED', 'Non traité'), ('NOT_AVAILABLE', 'Indisponible'), ('HANDLED', 'Préparé'), ('DELIVERY', 'Livré')], default='NOT_HANDLED', max_length=24)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apartment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.accessorytype')),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
                'unique_together': {('apartment', 'sheet')},
            },
        ),
    ]
