# Generated by Django 5.0.7 on 2024-07-20 15:28

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Un appartement portant ce nom éxiste déjà.'}, max_length=32, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bedroom', models.PositiveSmallIntegerField(default=1, validators=[project.models.MinValueValidator(1, 'Au moins 1 chambre ! On dort où sinon ?'), project.models.MaxValueValidator(12)], verbose_name='Chambre')),
                ('bathroom', models.PositiveSmallIntegerField(default=1, validators=[project.models.MaxValueValidator(6)], verbose_name='Salle de bain')),
                ('kitchen', models.PositiveSmallIntegerField(default=1, verbose_name='Cuisine')),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
            },
        ),
    ]
