# Generated by Django 5.0.7 on 2024-07-20 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom', to='main.room', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Salle de bain'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom', to='main.room', validators=[django.core.validators.MinValueValidator(1, 'Au moins 1 chambre ! On dort où sinon ?'), django.core.validators.MaxValueValidator(12)], verbose_name='Chambre'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='main.room', verbose_name='Cuisine'),
        ),
    ]
