# Generated by Django 5.0.7 on 2024-07-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_apartment_laundry_oom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='laundry_oom',
        ),
        migrations.AddField(
            model_name='apartment',
            name='laundry_room',
            field=models.BooleanField(default=False),
        ),
    ]
