# Generated by Django 5.0.7 on 2024-07-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_apartment_laundry_oom_apartment_laundry_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='laundry_room',
        ),
    ]
