# Generated by Django 5.0.7 on 2024-07-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_apartment_laundry_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='bathroom',
            new_name='number_of_bathrooms',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='bedroom',
            new_name='number_of_bedrooms',
        ),
        migrations.AddField(
            model_name='apartment',
            name='bathrooms',
            field=models.ManyToManyField(blank=True, related_name='+', to='project.room'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.ManyToManyField(blank=True, related_name='+', to='project.room'),
        ),
    ]
