# Generated by Django 5.0.7 on 2024-07-20 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_bathroom_apartment_number_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bathrooms',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Nombre de SDB'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bedrooms',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de chambre'),
        ),
    ]
