# Generated by Django 5.0.7 on 2024-07-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_apartment_number_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='+', to='main.room'),
        ),
    ]
