# Generated by Django 5.0.7 on 2024-07-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_apartment_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='bedrooms',
        ),
    ]
