# Generated by Django 5.0.7 on 2024-07-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_apartment_bathrooms_remove_apartment_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='rooms',
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.room'),
            preserve_default=False,
        ),
    ]
