# Generated by Django 5.0.7 on 2024-07-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_apartment_rooms_apartment_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='apartment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.apartment'),
            preserve_default=False,
        ),
    ]
