# Generated by Django 5.0.7 on 2024-07-20 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_room_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='project.apartment'),
        ),
    ]
