# Generated by Django 5.0.7 on 2024-07-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_room_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='apartment',
        ),
        migrations.AddField(
            model_name='room',
            name='apartment',
            field=models.ManyToManyField(related_name='apartment', to='project.apartment'),
        ),
    ]
