# Generated by Django 5.0.7 on 2024-07-20 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_remove_room_apartment_apartment_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='project.room'),
        ),
    ]
