# Generated by Django 5.0.7 on 2024-07-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_remove_apartment_kitchen_room_apartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='number_of_bathrooms',
            new_name='bathroom',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='number_of_bedrooms',
            new_name='bedroom',
        ),
    ]
